name: Sync
on: [ push ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Sync to Gitee
          uses: wearerequired/git-mirror-action@v1
          env:
            SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          with:
            source-repo: "git@github.com/ACFUN-FOSS/acfunlive-toolbox-client-Public.git"
            destination-repo: "git@gitee.com/acfun-foss/acfunlive-toolbox-client-Public.git"
